### PR TITLE
🏗 Build Spider: Los Angeles Board of Supervisors

### PR DESCRIPTION
**Pull request by cruznunez**
## What's this PR do?
This PR adds a Los Angeles County, CA scraper for Board of Supervisors. 

## Why are we doing this?
Scraper requested from [spreadsheet](https://docs.google.com/spreadsheets/d/1-HwPQKwm56vZ8h7CEM65GazKLTS0086gmaEzEHXp7O4/edit?usp=sharing).

## Steps to manually test
1. Ensure the project is installed:
```
pipenv sync --dev
```
2. Activate the virtual env and enter the pipenv shell:
```
pipenv shell
```
3. Run the spider:
```
scrapy crawl losca_Board_of_Supervisors -O test_output.csv
```
4. Monitor the output and ensure no errors are raised.
5. Inspect `test_output.csv` to ensure the data looks valid.
6. Ensure all tests pass
```
pytest
```

## Are there any smells or added technical debt to note?
None.

## Summary by CodeRabbit

- **New Features**
	- Introduced a new spider to scrape meeting information from the Los Angeles County Board of Supervisors, capturing details such as meeting titles, times, and locations.

- **Tests**
	- Implemented a comprehensive suite of unit tests to validate the functionality of the new spider, ensuring accurate data extraction and formatting.

### CODE REVIEW

**Comment by cruznunez** [comment]
The CI check is having trouble running the `pipenv sync --dev` command. It raises an error of

```py
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/city-scrapers-losca/city-scrapers-losca/.venv/bin/python'
```

This happened on my last commit, too. It passed after I reran the job. However, this time time I've rerun it like 3 times and it's still failing. Didn't want to keep retrying after that. Please advise.

**Review by lamle-ea — COMMENTED** [review]
Thank you for your work; your code looks great to me. I do have one concern regarding the document titles. Currently, both the Agency and Supplemental PDFs are labeled simply as "PDF," which could potentially confuse users on Documenters.org. To enhance clarity, I suggest we prepend these document titles with the appropriate document type, such as "Agency PDF" or "Supplemental PDF." What do you think?

**Comment by cruznunez** [comment]
@lamle-ea Good point I hadn't thought of that. Thank you. Updated.

**Review by lamle-ea — APPROVED** [review]
LGTM

**Pull request merged**
